#include <iostream>
#include "GameDie.h"
using namespace std;

int main()
{
	GameDie dieObj;
	int randumValue;
	randumValue = dieObj.roll();
	cout<<"Random number generated by game die is " << randumValue << endl;
	return 0;
}
